# Generated by Django 5.0.6 on 2024-06-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
