# Generated by Django 5.0.6 on 2024-09-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_alter_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='mpesa_ref',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
