# Generated by Django 5.0.6 on 2024-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenants', '0002_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='reciept',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
